ansible.builtin.command: per eseguire comando (quando non ci sono specifici moduli per il nostro task) - non è idempotetnte 
ansible.builtin.file: per creare directory
ansible.builtin.uri: test di connessione
ansible.builtin.reboot: riavviare
ansible.builtin.fail:
ansible.builtin.meta:
ansible.builtin.stat:
ansible.builtin.waitfor:
ansible.builtin.assert: 


